version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: yelm
      POSTGRES_PASSWORD: yelm_password
      POSTGRES_DB: yelm_country_carvings
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U yelm"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: