version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: .
    environment:
      - PORT=3000
      - POSTGRES_URL=postgres://${DB_USER}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH}
      - JWT_SECRET=${JWT_SECRET}
      - SMTP2GO_API_KEY=${SMTP2GO_API_KEY}
    ports:
      - "3000:3000"
    volumes:
      - ./packages/backend/img:/app/img
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
