export const facebookLink = 'https://www.facebook.com/profile.php?id=100063890677103';
export const organizerName = 'Yelm Country Carvings';
export const organizerEmail = process.env.VITE_ORGANIZER_EMAIL ?? 'tlzumach@hotmail.com';
export const smtpSenderEmail =
  process.env.VITE_SMTP_SENDER_EMAIL ?? 'yelmcountrycarvings@bitney.org';
export const adminName = process.env.VITE_ADMIN_NAME ?? 'Tracie';

export const inspirationalQuotes = [
  'Creativity is intelligence having fun. - Albert Einstein',
  'The best way to predict the future is to create it. - Peter Drucker',
  'Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. - Steve Jobs',
  'The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt',
  'Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer',
  "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
  'The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt',
  'Opportunities don’t happen, you create them. - Chris Grosser',
  'Success is not in what you have, but who you are. - Bo Bennett',
  'Push yourself, because no one else is going to do it for you. - Unknown',
  "Success isn't just about what you accomplish in your life; it's about what you inspire others to do. - Unknown",
  'It does not matter how slowly you go as long as you do not stop. - Confucius',
  'The way to get started is to quit talking and begin doing. - Walt Disney',
  'Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats',
  'Dream big and dare to fail. - Norman Vaughan',
  'What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar',
  'You are never too old to set another goal or to dream a new dream. - C.S. Lewis',
  'The harder you work for something, the greater you’ll feel when you achieve it. - Unknown',
  'Sometimes we’re tested not to show our weaknesses, but to discover our strengths. - Unknown',
  'Great things never come from comfort zones. - Unknown',
  'Believe you can and you’re halfway there. - Theodore Roosevelt',
  'The only way to do great work is to love what you do. - Steve Jobs',
  'Act as if what you do makes a difference. It does. - William James',
  'With the new day comes new strength and new thoughts. - Eleanor Roosevelt',
  'Happiness is not something ready-made. It comes from your own actions. - Dalai Lama',
  'Everything you’ve ever wanted is on the other side of fear. - George Addair',
  'Small deeds done are better than great deeds planned. - Peter Marshall',
  'Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman',
  "Perseverance is not a long race; it's many short races one after the other. - Walter Elliot",
  'It always seems impossible until it’s done. - Nelson Mandela',
  'If you want to lift yourself up, lift up someone else. - Booker T. Washington',
  'Start where you are. Use what you have. Do what you can. - Arthur Ashe',
  'Be yourself; everyone else is already taken. - Oscar Wilde',
  'Today is your opportunity to build the tomorrow you want. - Ken Poirot',
  'Don’t wait. The time will never be just right. - Napoleon Hill',
  'If you can dream it, you can do it. - Walt Disney',
  'Doubt kills more dreams than failure ever will. - Suzy Kassem',
  'Mistakes are proof that you are trying. - Jennifer Lim',
  'You miss 100% of the shots you don’t take. - Wayne Gretzky',
  'You are capable of amazing things. - Unknown',
  'Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. - Booker T. Washington',
  'Believe in yourself and all that you are. - Christian D. Larson',
  'You must do the things you think you cannot do. - Eleanor Roosevelt',
  'The most effective way to do it, is to do it. - Amelia Earhart',
  'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence. - Helen Keller',
  'The question isn’t who’s going to let me; it’s who is going to stop me. - Ayn Rand',
  'Passion is energy. Feel the power that comes from focusing on what excites you. - Oprah Winfrey',
  'You are your best thing. - Toni Morrison',
  'I never dreamed about success. I worked for it. - Estée Lauder',
];
